# Generated by Django 3.1.1 on 2021-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('contents', models.CharField(max_length=400)),
                ('write_date', models.DateTimeField()),
                ('store_id', models.IntegerField()),
                ('star', models.IntegerField()),
            ],
        ),
    ]
