# Generated by Django 3.1.1 on 2021-03-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210317_1045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
