# Generated by Django 3.1.1 on 2021-04-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210318_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('store_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Wish',
                'managed': False,
            },
        ),
    ]
