# Generated by Django 3.1.1 on 2021-03-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210317_1045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='Follow',
        ),
        migrations.AlterModelTable(
            name='like',
            table='Like',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
