# Generated by Django 3.1.1 on 2021-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviewcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fffood', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviewcategory',
                'managed': False,
            },
        ),
    ]
