# Generated by Django 3.1.1 on 2021-04-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanaged', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
